### ISSUE TITLE
MainUnit/beacon8pattern.txt cutoff

### ISSUE THREAD

**Issue by sundhaug92** [johnaho/Beacon8r#1]
MainUnit/beacon8pattern.txt#L191: ends with {, nothing after that

**Comment by dumpsterfirevip** [comment]
It does that on purpose!

This pattern is the top chunk of all the *.ino files that are output by /MainUnit/plugNChug.py
That plugNChug.py file does the not so heavy lifting of parsing a text file that is a huge list of words and turning them into programs that can be flashed onto esp8266's. The programs are limited by basic esp8266 memory size. 

So a complete output file where you can see partial output is provided here: MainUnit/ExampleOutput/beacon8rCluster_12.ino
 

What I did was create a super simple script that would paste in that beacon8pattern.txt file into the top part of a new file, wrap each of the lines in the file in a function call  and close it off at the end of each section of words as defined by line 18 "spliton" variable. 

I had a huge list so I split on something like 2900 and ended up having 40+ esp8266's programmed and running at once to pump the entire list out rather quick and honestly not that reliably to show up on a phone's AP list. A wifi scanner would show more of what it all outputs and I'm waiting on word from Dark Matter how much traffic I was pumping.
